### ISSUE TITLE
Android Todo

### ISSUE THREAD

**Issue by marcelklehr** [floccusaddon/floccus#965]
- [x] fix back button
- [x] fix Tree.vue updates
- [x] add i18n
- [ ] fix WebDAV
- [ ] fix Google Drive
- [ ] ~~Add telemetry?~~

**Comment by mnalis** [comment]
If by `telemetry` you mean sending any data (anonymized or not) from user device somewhere else (to some internet location not controlled and explicitly set up by a user), I would advise against doing that. 

The main reason some people use floccus is to avoid **any data leaving their control** without their explicit wish. Especially the ones using https://f-droid.org instead of Google app store for example. If there is a need to share debug info etc. to troubleshoot problems, the logs could be kept on device, and `share` button provided to send it via e-mail or whatever method (for example like [DavX5](https://gitlab.com/bitfireAT/davx5-ose/-/tree/master-ose) does it)

**Comment by marcelklehr** [comment]
@mnalis Thanks for your input! I'm also torn on telemetry as I don't like it myself. The purpose in this case would be to send errors and possibly which adapter people are using, so I can focus my efforts better. The latter could be done via a survey, while the former would just have to rely on people actively reporting issues. Both are fine for now.

**Comment by marcelklehr** [comment]
fml
